/// Generated by AssetsRefGenerator on 2022/08/02
class Res {
  static const String addusericon = "assets/Images/addusericon.svg";
  static const String addusersmall = "assets/Images/addusersmall.png";
  static const String cameraicon = "assets/Images/cameraicon.svg";
  static const String emailicon = "assets/Images/emailicon.svg";
  static const String locationicon = "assets/Images/locationicon.svg";
  static const String logogreen = "assets/Images/logogreen.svg";
  static const String logogreenupdaated = "assets/Images/logogreenupdaated.png";
  static const String otpicon = "assets/Images/otpicon.svg";
  static const String passwordicon = "assets/Images/passwordicon.svg";
  static const String personicon = "assets/Images/personicon.svg";
  static const String phonenumbericon = "assets/Images/phonenumbericon.svg";
}
